let questions = [
{
"info_quest": "1er Parcial 2024",
"numb": 1,
"question": "¿Cuál de los siguientes seres vivos cumple su papel como hospedero definitivo en la Equinococosis quística?",
"answer": ["Cánidos"],
"options": [
"Félidos",
"Bovinos",
"Cánidos",
"Humanos",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 2,
"question": "En el estudio parasitológico directo de un probable quiste hidático, ¿cuál de las siguientes estructuras parasitarias observadas confirman el diagnóstico?",
"answer": ["Protoescólices invaginados"],
"options": [
"Ejemplares adultos",
"Larvas rabditiformes",
"Protoescólices invaginados",
"Huevos con cubierta externa radiada",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 3,
"question": "¿Cuál es el fármaco de elección para el tratamiento médico de la Equinococosis quística?",
"answer": ["Albendazol"],
"options": [
"Fluconazol",
"Albendazol",
"Itraconazol",
"Metronidazol",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 4,
"question": "Paciente de 14 años vista por oftalmólogo porque comienza hace 3 días con dolor ocular, ojo rojo y visión borrosa en ojo derecho. En fondo de ojo derecho se observa: uveítis posterior con vitritis, además lesión única intensamente blanca focal y lesiones cicatrizales retinocoroideas con hiperpigmentación retiniana intensa. ¿Cuál es el diagnóstico presuntivo más probable?",
"answer": ["toxoplasmosis ocular"],
"options": [
"toxocariasis ocular",
"toxoplasmosis ocular",
"uveítis con vitritis por Candida spp",
"endoftalmitis por Aspergillus complex",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 5,
"question": "¿A través de qué zonas anatómicas u órganos migra la hembra grávida de Enterobius vermicularis hasta oviponer?",
"answer": ["Intestino grueso, recto y ano"],
"options": [
"Intestino grueso, recto y ano",
"Esófago, estómago e intestino grueso",
"Piel, corazón, pulmón e intestino grueso",
"Intestino delgado, corazón, pulmón y colon",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 6,
"question": "¿Por qué vía se transmite la parasitosis provocada por Enterobius vermicularis?",
"answer": ["Directa ano-mano-boca por ingesta de huevos larvados"],
"options": [
"Fecal oral por ingesta de huevos no embrionados",
"Directa ano-mano-boca por ingesta de huevos larvados",
"Fecal oral por ingesta de huevos con embrión hexacanto",
"Directa ano-mano-boca por ingesta de huevos no embrionados",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 7,
"question": "¿Cómo adquiere el ser humano la infección por Ascaris lumbricoides?",
"answer": ["por ingestión de huevos larvados presentes en el ambiente"],
"options": [
"por ingestión de quistes presentes en carnes mal cocidas",
"por ingestión de huevos larvados presentes en el ambiente",
"por consumo de metacercarias presentes en el berro silvestre",
"por penetración transcutánea de larvas libres en el medio exterior",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 8,
"question": "¿Cuál de los siguientes mecanismos patogénicos corresponden a Ascaris lumbricoides?",
"answer": ["Acción bacterífera por pasaje de larvas desde lumen intestinal hacia el torrente sanguíneo"],
"options": [
"Acción expoliatriz por el consumo de sangre por los parásitos",
"Acción mecánica por obstrucción venosa por ovillos de ejemplares adultos",
"Acción traumática por pasaje de larvas desde la mucosa hacia la luz intestinal",
"Acción bacterífera por pasaje de larvas desde lumen intestinal hacia el torrente sanguíneo",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 9,
"question": "¿En cuál de las siguientes presentaciones clínicas es Giardia lamblia el agente más frecuente?",
"answer": ["Diarrea de causa parasitaria en niños en edad escolar"],
"options": [
"Enteritis sub aguda en pacientes inmunodeprimidos",
"Diarrea de causa parasitaria en niños en edad escolar",
"Diarrea aguda en inmunocompetentes de cualquier rango etario",
"Enteritis con sangre y moco en las heces en adultos inmunocompetentes",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 10,
"question": "¿Cuál de los siguientes mecanismos patogénicos es uno de los que corresponde a los producidos por Giardia lamblia a nivel intestinal?",
"answer": ["acción traumática por adhesión del disco suctor, enzimática por proteinasas y tóxica con producción de atrofia vellositaria"],
"options": [
"lisis de los enterocitos infectados por invasión, multiplicación y liberación de los parásitos",
"lisis sobre vellosidades intestinales por la liberación de vesículas que contienen gránulos",
"aumento de la permeabilidad de la célula blanco a través de un péptido denominado amebaporo",
"acción traumática por adhesión del disco suctor, enzimática por proteinasas y tóxica con producción de atrofia vellositaria",
"lesión por penetración del extremo anterior en la mucosa intestinal determinando hiperemia, reacción inflamatoria y eosinófilos en la zona afectada",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 11,
"question": "¿Cuál de los siguientes helmintos presenta un ciclo monoxeno?",
"answer": ["Enterobius vermicularis"],
"options": [
"Taenia saginata",
"Fasciola hepatica",
"Enterobius vermicularis",
"Echinococcus granulosus",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 12,
"question": "¿Cuál de los siguientes patógenos entéricos es un helminto transmitido por el suelo?",
"answer": ["Trichuris trichiura"],
"options": [
"Taenia saginata",
"Trichuris trichiura",
"Dipylidium caninum",
"Enterobius vermicularis",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 13,
"question": "¿Cuál es la forma infectante de Toxocara canis para el ser humano?",
"answer": ["huevos larvados liberados al ambiente en las heces de los perros hace 1 a 4 semanas"],
"options": [
"huevos recién liberados en las heces de los perros al ambiente",
"larvas recién liberadas en las heces de perras gestantes al ambiente",
"larvas liberadas al ambiente en las heces de los perros hace 1 a 4 semanas",
"huevos larvados liberados al ambiente en las heces de los perros hace 1 a 4 semanas",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 14,
"question": "¿Cuál es el alimento de Pediculus humanus var capitis?",
"answer": ["sangre del cuero cabelludo"],
"options": [
"detritus celulares",
"bacterias de la piel",
"células de piel muerta",
"sangre del cuero cabelludo",
"grasa de las glándulas sebáceas",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 15,
"question": "¿Qué fármaco podemos utilizar de forma tópica para el tratamiento de la infección por Pediculus humanus var capitis?",
"answer": ["Permetrina"],
"options": [
"Pirantel",
"Piperazina",
"Permetrina",
"Paromomicina",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 16,
"question": "¿Cuál de las siguientes condiciones es un factor de riesgo para presentar aspergilosis invasiva?",
"answer": ["Neutropenia profunda y mantenida"],
"options": [
"Trombocitopenia",
"Déficit de complemento",
"Anemia microcítica e hipocrómica",
"Neutropenia profunda y mantenida",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 17,
"question": "¿Cuál de los siguientes dermatofitos es geofílico?",
"answer": ["Nannizzia gypsea"],
"options": [
"Nannizzia gypsea",
"Microsporum canis",
"Trichophyton rubrum",
"Trichophyton interdigitale",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 18,
"question": "¿Qué estructuras son fundamentales de observar en el examen micológico directo para realizar con certeza diagnóstico de candidiasis superficial?",
"answer": ["levaduras uni brotantes y seudofilamentos"],
"options": [
"filamentos verdaderos",
"macroconidios verrucosos",
"levaduras uni brotantes y seudofilamentos",
"microconidios y macroconidios característicos",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 19,
"question": "¿Cuál de las siguientes patologías es producida por levaduras del género Malassezia?",
"answer": ["Pitiriasis versicolor"],
"options": [
"Tiña pedis",
"Muguet oral",
"Vulvovaginitis",
"Pitiriasis versicolor",
"Dermatitis del pañal",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 20,
"question": "Lactante de 2 meses de vida, llevado al pediatra para control. Durante el examen físico se observa eritema en zona de pañal y exudado blanco, grumoso en pliegue inguinal. Se solicita un estudio micológico. <br> ¿Qué espera ver en el informe del estudio micológico de las zonas afectadas?",
"answer": ["Examen directo: se observan levaduras con pseudofilamentos. Cultivos: Desarrolla Candida albicans"],
"options": [
"Examen directo: se observan levaduras con pseudofilamentos. Cultivos: Desarrolla Candida albicans",
"Examen directo: se observan levaduras mono brotantes. Cultivos: Desarrolla Histoplasma capsulatum",
"Examen directo: se observan levaduras multi brotantes. Cultivos: Desarrolla Paracoccidioides spp.",
"Examen directo: No se observan estructuras fúngicas. Cultivos: Desarrolla Sporothrix sp.",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 21,
"question": "¿Qué características morfológicas presenta y qué tejidos afecta el hongo Sporothrix sp?",
"answer": ["Es un hongo dimorfo que afecta la dermo-hipodermis y puede generar linfangitis"],
"options": [
"Es un hongo levaduriforme que afecta a las faneras",
"Es un hongo filamentoso que afecta la piel y las faneras",
"Es un hongo dimorfo que afecta a faneras y puede generar linfangitis",
"Es un hongo dimorfo que afecta la dermo-hipodermis y puede generar linfangitis",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 22,
"question": "¿Cuál es el mecanismo por el que se adquiere la esporotricosis?",
"answer": ["Implantación de conidios"],
"options": [
"Ingestión de conidios",
"Ingestión de levaduras",
"Implantación de conidios",
"Implantación de levaduras",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 23,
"question": "¿Cuál es el fármaco de elección para el tratamiento de la esporotricosis?",
"answer": ["Itraconazol"],
"options": [
"Fluconazol",
"Albendazol",
"Itraconazol",
"Metronidazol",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 24,
"question": "¿Cuál de las siguientes parasitosis puede ser transmitida por vectores biológicos?",
"answer": ["Enfermedad de Chagas"],
"options": [
"Toxoplasmosis",
"Neurocisticercosis",
"Equinococosis quística",
"Enfermedad de Chagas",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 25,
"question": "¿Cómo se llama el vector de la leishmaniasis presente en nuestro país?",
"answer": ["Lutzomyia longipalpis"],
"options": [
"Aedes aegypti",
"Triatoma infestans",
"Anopheles gambiae",
"Lutzomyia longipalpis",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 26,
"question": "¿Cuál de las siguientes virosis que se presentan como problemas actuales de salud pública se transmite a través de mosquitos del género Culex?",
"answer": ["encefalitis equina"],
"options": [
"dengue",
"covid-19",
"influenza",
"encefalitis equina",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 27,
"question": "¿Cuál de las siguientes medidas de control sobre Aedes aegypti se recomienda implementar por la población?",
"answer": ["Tapar herméticamente tanques, barriles y otros depósitos de agua"],
"options": [
"Colocar collares repelentes con deltametrina a los perros",
"Alejar de la vivienda, gallineros y otros refugios de animales",
"Tapar herméticamente tanques, barriles y otros depósitos de agua",
"Evitar la acumulación de ramas y otros residuos vegetales en el peridomicilio",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 28,
"question": "¿Qué etapa del ciclo de vida del mosquito Aedes aegypti es capaz de resistir la desecación y temperaturas extremas?",
"answer": ["Huevo"],
"options": [
"Pupa",
"Larva",
"Huevo",
"Adulto",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 29,
"question": "¿Cuál de los siguientes patógenos hemotesiduales tiene mecanismo de transmisión vectorial?",
"answer": ["Leishmania infantum"],
"options": [
"Toxocara canis",
"Toxoplasma gondii",
"Leishmania infantum",
"Histoplasma capsulatum",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 30,
"question": "¿En qué etapa del embarazo es más probable que ocurriendo una infección aguda por Toxoplasma gondii se produzca la transmisión vertical?",
"answer": ["Tercer trimestre"],
"options": [
"Primer trimestre",
"Segundo trimestre",
"Tercer trimestre",
"Sin diferencia entre trimestres",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 31,
"question": "En el mecanismo de transmisión oral de la toxoplasmosis en el ser humano, ¿cuál es la forma infectante de Toxoplasma gondii y en qué alimentos se puede encontrar?",
"answer": ["ooquistes en frutas y verduras mal lavadas y en agua de consumo"],
"options": [
"ooquistes tisulares en carnes de consumo humano bien cocidas",
"ooquistes en frutas y verduras mal lavadas y en agua de consumo",
"ooquistes tisulares en carnes de consumo humano escasamente cocidas",
"quistes tisulares en frutas y verduras mal lavadas y en agua de consumo",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 32,
"question": "¿Qué pruebas de anticuerpos debe incluir inicialmente el tamizaje serológico de la embarazada para detectar toxoplasmosis?",
"answer": ["IgG e IgM específicas anti Toxoplasma"],
"options": [
"IgG, IgM e IgE totales",
"Test de avidez de IgG",
"IgG e IgM específicas anti Toxoplasma",
"IgM, IgA e IgE específicas anti Toxoplasma",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 33,
"question": "¿Qué técnica es de utilidad como método de tamizaje de toxoplasmosis en embarazadas?",
"answer": ["Ensayo inmunoenzimático (ELISA)"],
"options": [
"Sabin y Feldman",
"Hemaglutinación",
"Inmunofluorescencia",
"Ensayo inmunoenzimático (ELISA)",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 34,
"question": "Recibe test de Chagas positivo de una paciente como parte de sus rutinas obstétricas. ¿Cómo confirma el diagnóstico de enfermedad de Chagas?",
"answer": ["con dos pruebas serológicas positivas, de principio diferente, para enfermedad de Chagas"],
"options": [
"con dos pruebas serológicas positivas, de principio diferente, para enfermedad de Chagas",
"con dos pruebas parasitológicas positivas practicadas con 21 días de diferencia entre ellas",
"con el dato epidemiológico de la procedencia de la paciente y el de la serología de su madre",
"con electrocardiograma y/o ecocardiograma que presenten signos patognomónicos de enfermedad de Chagas",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 35,
"question": "¿En qué etapa del embarazo es más probable la transmisión vertical de la Enfermedad de Chagas?",
"answer": ["Sin diferencia entre trimestres"],
"options": [
"Primer trimestre",
"Segundo trimestre",
"Tercer trimestre",
"Sin diferencia entre trimestres",
],
"discipline": "Parasito",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 36,
"question": "¿Cuál de las siguientes formas clínicas de la enfermedad de Chagas requiere tratamiento farmacológico?",
"answer": ["Lactantes con diagnóstico de enfermedad de Chagas congénito", "Adultos con enfermedad de Chagas en etapa crónica sintomática"],
"options": [
"Vólvulo del sigmoide con oclusión intestinal",
"Lactantes con diagnóstico de enfermedad de Chagas congénito",
"Embarazadas con serología reactiva para enfermedad de Chagas",
"Adultos con enfermedad de Chagas en etapa crónica sintomática",
],
"discipline": "Parasito",
"comment": "esta pregunta es ambigua. B y D.",
},
{
"info_quest": "1er Parcial 2024",
"numb": 37,
"question": "Embarazada de 34 años, residente de Montevideo. Vivió hasta los 17 años en Paysandú. <br> Su madre falleció por evento cardiovascular que no especifica. Abuela desconocida. Cursa embarazo de 16 semanas. Antecedentes Gineco-obstétricos: 2 gestas, 2 partos vaginales (último hace 10 años). No se cuenta con la información de los controles de los embarazos previos. Consulta con los resultados de serología para enfermedad de Chagas y Toxoplasmosis. <br> enfermedad de Chagas: resultado reactivo - técnica ELISA<br> toxoplasmosis: resultado IgG reactivo; IgM no reactivo - técnica ELISA <br> ¿Cómo se interpretan estos resultados?",
"answer": ["es necesario confirmar la infección por T. cruzi con otra técnica serológica mientras que los resultados para T. gondii implican exposición previa y no requieren confirmación"],
"options": [
"es necesario confirmar la infección por T. cruzi con otra técnica serológica y la infección por T. gondii mediante un test de avidez",
"no es necesario nuevos estudios ya que los resultados serológicos indican exposición previa para ambas enfermedades",
"es necesario confirmar la infección por T. cruzi con otra técnica serológica mientras que los resultados para T. gondii implican exposición previa y no requieren confirmación",
"no es necesario confirmar la infección por T. cruzi con otra técnica serológica ya que los resultados indican exposición previa y si es necesario confirmar la infección aguda por T gondii mediante un test de avidez",
],
"discipline": "Parasito",
"comment": "",
},
// 38 anulada
{
"info_quest": "1er Parcial 2024",
"numb": 39,
"question": "ndique cuál de los siguientes microorganismos, agentes de gastroenterocolitis aguda, presenta como mecanismo patogénico el ingreso al enterocito, y la capacidad de moverse en el citoplasma y desplazarse a células vecinas mediante polimerización de la actina.",
"answer": ["Shigella"],
"options": [
"Shigella",
"Rotavirus",
"Salmonella",
"Escherichia coli enterotoxigénica",
"Escherichia coli enterohemorrágica",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 40,
"question": "El mecanismo por el cual Escherichia coli enteropatogénica causa diarrea es:",
"answer": ["Por alteración en la absorción debido al borramiento de las microvellosidades y la formación de una estructura en forma de pedestal sobre la cual se adhieren las bacterias"],
"options": [
"Por producción de toxinas termolábil y termoestable que aumentan la secreción de cloro y agua a la luz intestinal",
"Por producción de toxina shiga (Stx) con actividad citotóxica sobre el enterocito, alterando así la absorción intestinal",
"Por alteración en la absorción debido al borramiento de las microvellosidades y la formación de una estructura en forma de pedestal sobre la cual se adhieren las bacterias",
"Por ingreso al ambiente intracelular de los enterocitos mediante la inyección de proteínas efectoras secretadas por el sistema de secreción tipo 3 induciendo la muerte celular por apoptosis",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 41,
"question": "Para el tratamiento de algunos cuadros de diarrea disenteriforme está indicado el uso de azitromicina. ¿Cuál es el mecanismo de acción de este antibiótico?",
"answer": ["Inhibir la síntesis de proteínas"],
"options": [
"Inhibir la replicación del ADN",
"Inhibir la síntesis de proteínas",
"Bloquear la síntesis de ácido fólico",
"Inhibir la síntesis de la pared bacteriana",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 42,
"question": "En la patogenia de la infección del tracto urinario, Escherichia coli invade la célula del epitelio vesical formando comunidades bacterianas intracelulares. Esto le permite:",
"answer": ["evadir la acción de la respuesta inmune"],
"options": [
"evadir la acción de la respuesta inmune",
"activar la muerte celular programada en la célula epitelial vesical",
"acceder a la membrana basal y de allí al torrente sanguíneo causando bacteriemia",
"desplazarse de célula a célula intracelularmente exacerbando la respuesta inflamatoria",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 43,
"question": "En una mujer joven con cistitis, se toma una muestra de orina para urocultivo y se realiza una tira reactiva de orina que revela un resultado positivo para esterasas leucocitarias y negativo para nitritos. Considerando la edad de la paciente y el resultado de la tira reactiva, el agente etiológico de la cistitis es probablemente:",
"answer": ["Staphylococcus saprophyticus"],
"options": [
"Escherichia coli",
"Proteus mirabilis",
"Staphylococcus aureus",
"Staphylococcus saprophyticus",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 44,
"question": "Una cepa de Escherichia coli aislada a partir de una infección urinaria, presenta el siguiente perfil de susceptibilidad a antibióticos: <br> Resistente a ampicilina, cefazolina y trimetoprim sulfametoxazol <br>Sensible a amoxicilina clavulánico, cefuroxime, nitrofurantoína y fosfomicina <br>¿Cuál es el mecanismo más probable de resistencia a betalactámicos en esta cepa?",
"answer": ["Producción de betalactamasas de espectro ampliado"],
"options": [
"Producción de betalactamasas de espectro ampliado",
"Producción de betalactamasas de espectro extendido",
"Modificación del sitio blanco por adquisición de un nuevo tipo de PBP",
"Modificación del sitio blanco por acumulación de cambios en una PBP",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 45,
"question": "Considerando que la cepa de E.coli de la pregunta anterior fue aislada de un caso de pielonefritis. ¿Cuál de los antibióticos evaluados es de elección para el tratamiento?",
"answer": ["Cefuroxime"],
"options": [
"Cefuroxime",
"Nitrofurantoína",
"Fosfomicina trometamol",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 46,
"question": "En un paciente con un cuadro de encefalitis de probable etiología viral, se realiza punción lumbar para extraer líquido cefalorraquídeo ¿Qué características se espera encontrar en el estudio citoquímico del líquido cefalorraquídeo?",
"answer": ["Aspecto claro, valores normales de glucosa y celularidad aumentada"],
"options": [
"Aspecto turbio, valores normales de glucosa y celularidad normal",
"Aspecto claro, valores disminuidos de glucosa y celularidad normal",
"Aspecto turbio, valores disminuidos de glucosa y celularidad normal",
"Aspecto claro, valores normales de glucosa y celularidad aumentada",
"Aspecto turbio, valores disminuidos de glucosa y celularidad aumentada",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 47,
"question": "En un paciente con diagnóstico de encefalitis de probable etiología herpética, se inicia tratamiento empírico con Aciclovir endovenoso. ¿Cuál es el mecanismo de acción de este antiviral?",
"answer": ["Actúa como análogo de la desoxi-guanosina interrumpiendo la replicación del genoma viral"],
"options": [
"Actúa como análogo de los receptores celulares impidiendo la adsorción viral a la célula",
"Actúa como análogo de la desoxi-guanosina interrumpiendo la replicación del genoma viral",
"Actúa inhibiendo específicamente la neuraminidasa impidiendo la liberación de la progenie viral",
"Actúa inhibiendo específicamente la ARN polimerasa viral impidiendo la síntesis de los mensajeros virales",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 48,
"question": "Los Enterovirus son una de las causas más frecuentes de meningitis. ¿Cuál de las siguientes opciones corresponde con las características estructurales de las partículas virales de Enterovirus?",
"answer": ["Son virus desnudos y con genoma de ARN de simple hebra y polaridad positiva"],
"options": [
"Son virus con envoltura y genoma de ARN doble hebra",
"Son virus desnudos con genoma de ADN doble hebra",
"Son virus con envoltura y genoma de ADN de simple hebra y polaridad positiva",
"Son virus con envoltura y genoma de ARN de simple hebra y polaridad negativa",
"Son virus desnudos y con genoma de ARN de simple hebra y polaridad positiva",

],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 49, 
"question": "En un paciente de 18 meses se realiza diagnóstico de meningoencefalitis. El líquido cefalorraquídeo extraído por punción lumbar se procesa para estudio citoquímico y microbiológico. <br>El cititoquímico revela turbidez e hipo-glucorraquia. El examen microscópico directo, muestra predominancia de células polimorfonucleares y diplococos Gram positivos. <br> En base a estos hallazgos, ¿cuál es el agente más probable de este caso?",
"answer": ["Streptococcus pneumoniae"],
"options": [
"Neisseria meningitidis",
"Listeria monocytogenes",
"Streptococcus agalactiae",
"Streptococcus pneumoniae",
"Haemophylus influenzae de tipo b",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 50,
"question": "Neisseria meningitidis es uno de los principales agentes de meningoencefalitis aguda supurada y presenta variados factores de virulencia. ¿Cuál de los siguientes factores resulta esencial para persistir en el torrente sanguíneo?",
"answer": ["polisacárido capsular"],
"options": [
"toxinas citotóxicas",
"polisacárido capsular",
"adhesinas no fimbriales",
"endotoxina del lipo-oligosacárido",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 51,
"question": "¿Cómo está compuesta la vacuna antineumocócica incluida en el certificado esquema de vacunación de nuestro país que se administra a los 2, 4 y 12 meses de vida?",
"answer": ["Por 13 tipos diferentes de polisacáridos capsulares conjugados a proteínas"],
"options": [
"Por 13 tipos diferentes de polisacáridos capsulares conjugados a proteínas",
"Por 23 tipos diferentes de polisacáridos capsulares conjugados a proteínas",
"Por bacterias inactivadas de 13 tipos diferentes de polisacáridos capsulares",
"Por bacterias inactivadas de 23 tipos diferentes de polisacáridos capsulares",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 52,
"question": "¿A qué se debe la resistencia adquirida a beta-lactámicos en cepas de Streptococcus pneumoniae?",
"answer": ["eventos de transformación y recombinación en los genes codificantes para PBP"],
"options": [
"hiperproducción de PBP",
"adquisición de genes codificantes de beta-lactamasas",
"adquisición de un nuevo gen de PBP con baja afinidad",
"eventos de transformación y recombinación en los genes codificantes para PBP",
"acumulación de mutaciones puntuales en los genes de PBP que resultan en la disminución de la afinidad",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 53,
"question": "La muestra de expectoración es de elección para realizar el diagnóstico microbiológico de los casos de neumonía aguda. ¿Qué condición debe cumplir la muestra para ser validada en el laboratorio de bacteriología?",
"answer": ["El examen microscópico directo con tinción de Gram debe revelar una predominancia de células polimorfonucleares sobre las células epiteliales"],
"options": [
"El examen microscópico directo con tinción de Gram debe revelar una abundante celularidad",
"El examen microscópico directo con tinción de Gram debe revelar morfologías bacterianas características de los agentes causales de neumonia",
"El examen microscópico directo con tinción de Gram debe revelar una predominancia de células polimorfonucleares sobre las células epiteliales",
"El cultivo en medios ricos como agar sangre y agar chocolate, debe evidenciar un cultivo monomicrobiano",
"El cultivo en medios ricos como agar sangre y agar chocolate, debe evidenciar un cultivo con recuento mayor a 100.000 UFC/mL",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 54,
"question": "¿Cuál de las siguientes características de Influenza A se asocia a la ocurrencia de saltos antigénicos?",
"answer": ["Poseen genoma de ARN segmentado y pueden infectar distintas especies animales"],
"options": [
"Poseen dos tipos distintos de espículas de superficie insertas en la envoltura",
"Poseen genoma de ARN segmentado y pueden infectar distintas especies animales",
"Poseen genoma de ARN por lo que ocurre un proceso de acumulación de mutaciones",
"Poseen ARN polimerasas propias cuya actividad no es corregida en la célula por lo que se acumulan mutaciones",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 55,
"question": "El Oseltamivir es un fármaco utilizado para el tratamiento de la enfermedad severa causada por virus Influenza ¿Cuál es su mecanismo de acción?",
"answer": ["Inhibe la neuroaminidasa viral interfiriendo así en el egreso de las partículas virales de la célula"],
"options": [
"Inhibe el reconocimiento de la hemaglutinina viral con el receptor de ácido siálico celular",
"Inhibe la neuroaminidasa viral interfiriendo así en el egreso de las partículas virales de la célula",
"Inhibe la encapsidación de los segmentos genómicos de influenza al momento del egreso de la célula",
"Inhibe la elongación durante la replicación del genoma viral, ya que es un análogo de nucleósido que carece de grupo OH",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 56,
"question": "¿En qué grupo etario son más frecuentes los casos de faringitis producidas por Streptococcus pyogenes?",
"answer": ["Entre 5 y 15 años"],
"options": [
"Menores de 3 años",
"Entre 5 y 15 años",
"Entre 18 y 60 años",
"Mayores de 65 años",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 57,
"question": "Streptococcus pyogenes presenta diversos factores de virulencia que utiliza en su proceso patogénico. ¿Cuál de los siguientes factores participa facilitando la adherencia, invasión de las células epiteliales y evasión de la fagocitocis?",
"answer": ["Proteína M"],
"options": [
"Streptolisina O",
"Streptolisina S",
"Proteína M",
"Cápsula",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 58,
"question": "Considerando los procesos infecciosos causados por cepas de Staphylococcus aureus ¿cuál de los siguientes mecanismos es el que causa resistencia a la mayoría de los antibióticos beta-lactámicos utilizados en la clínica para el tratamiento de estas infecciones?",
"answer": ["modificaciones del sitio blanco"],
"options": [
"engrosamiento de pared",
"modificaciones del sitio blanco",
"pérdida en la expresión de porinas",
"enzimas modificadoras del antibiótico"
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 59,
"question": "De los siguientes factores de virulencia de Staphylococcus aureus ¿cuál es el más relevante en el Síndrome de Piel Escaldada?",
"answer": ["exotoxinas exfoliativas"],
"options": [
"proteína M",
"estreptolisina O",
"exotoxinas exfoliativas",
"proteína de unión a colágeno",
],
"discipline": "Bacterio",
"comment": "",
},
{
"info_quest": "1er Parcial 2024",
"numb": 60,
"question": "Considerando la infección por el virus varicela-zóster (VVZ) ¿cuál de los siguientes es el modelo de infección carácterístico de estos virus?",
"answer": ["latente"],
"options": [
"transformante",
"crónica",
"latente",
"aguda",
],
"discipline": "Bacterio",
"comment": "",
},
];