let questions = [
    {
    "info_quest": "3er Parcial 2024",
    "numb": 1,
    "question": "Un hombre de 72 años con antecedentes de cardiopatía isquémica es ingresado por insuficiencia cardíaca aguda con edema periférico, disnea y ortopnea. <br> De la paraclínica inicial Creatinina sérica: 2.8 mg/dL (previa conocida: 1.2 mg/dL). <br> Se inicia tratamiento con diuréticos intravenosos y soporte inotrópico, y la creatinina a los 3 días del ingreso es de 1.3 mg/dl. <br> ¿Qué tipo de injuria renal aguda presentó el paciente?",
    "answer": ["Pre-renal"],
    "options": [
    "Pre-renal",
    "Post-renal",
    "Rarenquimatosa de etiología isquémica",
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 2,
    "question": "¿Cuál de los siguientes fármacos puede agravar la injuria renal aguda isquémica por hipovolemia?",
    "answer": ["Inhibidores de la enzima convertidora de angiotensina"],
    "options": [
    "Antagonistas de los canales de calcio",
    "Antagonistas de los receptores beta-adrenérgicos",
    "Inhibidores de la enzima convertidora de angiotensina",
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 3,
    "question": "¿Cuánto tiempo suele demorar en mejorar la función renal en un paciente con necrosis tubular aguda isquémica, una vez resuelta la causa subyacente?",
    "answer": ["7 a 21 días"],
    "options": [
    "24 a 48 horas",
    "7 a 21 días",
    "4 a 6 semanas",
    "Más de 3 meses"
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 4,
    "question": "¿Cuánto debe disminuir el filtrado glomerular (FG) para que los niveles de creatinina sérica superen los valores normales?",
    "answer": ["50% del FG normal"],
    "options": [
    "10% del FG normal",
    "50% del FG normal",
    "75% del FG normal",
    "90% del FG normal"
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 5,
    "question": "¿Cuál de los siguientes factores puede contribuir a la hiperfiltración glomerular y a la progresión de la enfermedad renal crónica?",
    "answer": ["Obesidad"],
    "options": [
    "Obesidad",
    "Dieta hipoproteica",
    "Restricción calórica estricta",
    "Uso de inhibidores de la enzima convertidora de angiotensina (IECA)"
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 6,
    "question": "¿Qué ocurre con los podocitos durante la progresión de la enfermedad renal crónica?",
    "answer": ["Disminuyen en número por apoptosis y desprendimiento."],
    "options": [
    "Se regeneran a partir de células madre",
    "Aumentan en número para compensar el daño.",
    "Aumentan el espesor para resistir el estrés mecánico",
    "Disminuyen en número por apoptosis y desprendimiento."
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 7,
    "question": "Indique cuál de los siguientes trastornos del medio interno es uno de los principales mecanismos de daño neurológico secundario en la práctica clínica:",
    "answer": ["Hiponatremia"],
    "options": [
    "Hiponatremia",
    "Hipocalcemia",
    "Hipopotasemia",
    "Hipomagnesemia"
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 8,
    "question": "En un sector de parénquima cerebral injuriado con autorregulación abolida, ¿cuál de los siguientes fenómenos puede dar lugar a hipertensión endocraneana por hiperflujo cerebral?",
    "answer": ["Hipertensión arterial"],
    "options": [
    "Hipotermia",
    "Hipocapnia",
    "Hipotensión arterial",
    "Hipertensión arterial"
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 9,
    "question": "La hiperventilación es una medida efectiva para reducir la hipertensión endocraneana, ¿sobre qué parámetro actúa para ejercer este efecto?",
    "answer": ["La presión parcial de CO2 arterial"],
    "options": [
    "El metabolismo cerebral",
    "La temperatura sistémica",
    "La presión arterial sistémica",
    "La presión parcial de CO2 arterial"
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 10,
    "question": "En la insuficiencia cardíaca crónica, ¿cómo se encuentran típicamente los niveles de endotelina?",
    "answer": ["Aumentados, contribuyendo a la progresión de la enfermedad."],
    "options": [
    "Disminuidos, debido a la vasodilatación compensatoria.",
    "Normales, ya que no se altera su regulación en esta condición.",
    "Aumentados, contribuyendo a la progresión de la enfermedad.",
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 11,
    "question": "En la insuficiencia cardíaca con fracción de eyección del ventrículo izquierdo (FEVI) preservada, ¿cómo se encuentra la presión diastólica final del ventrículo izquierdo?",
    "answer": ["Aumentada, debido a la disfunción diastólica del ventrículo izquierdo."],
    "options": [
    "Disminuida, debido a una relajación ventricular adecuada.",
    "Normal, debido a la ausencia de alteraciones diastólicas.",
    "Aumentada, debido a la disfunción diastólica del ventrículo izquierdo.",
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 12,
    "question": "¿Cómo se encuentra el contenido de calcio en el retículo sarcoplásmico de los miocitos en la insuficiencia cardíaca?",
    "answer": ["Disminuido, por alteraciones en la recaptación de calcio"],
    "options": [
    "Disminuido, por alteraciones en la recaptación de calcio",
    "Normal, ya que no se altera la función del retículo sarcoplásmico",
    "Aumentado, debido a una hiperactividad de la SERCA2a",
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 13,
    "question": "¿Cómo influye un aumento en la frecuencia cardíaca sobre el consumo de oxígeno del miocardio?",
    "answer": ["Aumenta el consumo de oxígeno debido al incremento en el trabajo cardíaco"],
    "options": [
    "Disminuye el consumo de oxígeno al reducir la duración de la sístole.",
    "Aumenta el consumo de oxígeno debido al incremento en el trabajo cardíaco",
    "No afecta el consumo de oxígeno, ya que la frecuencia cardíaca no influye en el metabolismo miocárdico",
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 14,
    "question": "¿Cómo se encuentra la reserva de flujo sanguíneo coronario en pacientes con hipertrofia ventricular patológica severa?",
    "answer": ["Disminuida"],
    "options": [
    "Disminuida",
    "Normal",
    "Aumentada",
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 15,
    "question": "¿Qué es el hibernamiento cardíaco?",
    "answer": ["Una respuesta fisiológica del miocardio ante la disminución crónica del flujo sanguíneo coronario"],
    "options": [
    "Una respuesta fisiológica ante episodios de isquemia aguda",
    "Una respuesta fisiológica del miocardio ante la disminución crónica del flujo sanguíneo coronario",
    "Una respuesta patológica en la que el miocardio aumenta su actividad metabólica debido a la insuficiencia cardiaca",
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 16,
    "question": "A un paciente con sospecha de hipertensión pulmonar se le realiza un cateterismo cardíaco derecho y se obtienen los siguientes datos: PAPm = 47 mmHg, PAOP = 11 mmHg, RVP = 6 uW <br> ¿Cuál de las siguientes afirmaciones es correcta con respecto al perfil hemodinámico?",
    "answer": ["Se trata de una hipertensión pulmonar precapilar"],
    "options": [
    "El gradiente transpulmonar es 7",
    "Se trata de una hipertensión pulmonar precapilar",
    "Se trata de una hipertensión pulmonar combinada",
    "Se trata de una hipertensión pulmonar poscapilar aislada"
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 17,
    "question": "Durante un cateterismo cardíaco derecho con un catéter de Swan-Ganz, se mide la presión de oclusión pulmonar (PAOP). ¿Qué presión se está estimando de manera indirecta con esta medición?",
    "answer": ["La presión auricular izquierda"],
    "options": [
    "La presión aórtica media",
    "La presión auricular derecha",
    "La presión auricular izquierda",
    "La presión diastólica final del ventrículo derecho"
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 18,
    "question": "¿Cómo es el flujo sanguíneo coronario a través del sistema coronario derecho en condiciones normales?",
    "answer": ["Es sisto-diastólico"],
    "options": [
    "Es sistólico",
    "Es diastólico.",
    "Es sisto-diastólico",
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 19, 
    "question": "¿Cómo se encuentran los niveles de péptidos natriuréticos biológicamente activos, en un paciente con insuficiencia cardíaca severa? ",
    "answer": ["Disminuidos"],
    "options": [
    "Disminuidos",
    "Normales",
    "Aumentados",
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 20,
    "question": "La hipertensión arterial crónica, se asocia con hipertrofia miocárdica, que en etapas iniciales suele ser:",
    "answer": ["Concéntrica"],
    "options": [
    "Mixta",
    "Excéntrica",
    "Concéntrica",
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 21,
    "question": "Con respecto a los determinantes de la presión arterial, las resistencias vasculares sistémicas dependen de:",
    "answer": ["Las propiedades de las arteriolas precapilares"],
    "options": [
    "El shear stress",
    "El gasto cardíaco",
    "Las propiedades de las arteriolas precapilares",
    "Las propiedades de los grandes vasos de capacitancia"
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 22,
    "question": "¿Qué determina las ondas reflejadas que alcanzan la aorta ascendente durante la diástole precoz posterior a la incisura dícrota?",
    "answer": ["Aumento de la onda de presión"],
    "options": [
    "Aumento de la onda de presión",
    "Disminución de la onda de presión",
    "Eliminación completa de la onda de presión",
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 23,
    "question": "¿Cuál de las siguientes es una alteración característica de la insuficiencia hepatocítica?",
    "answer": ["Disminución en la producción de factores de la coagulación"],
    "options": [
    "Aumento de la síntesis plasmática de proteínas",
    "Disminución en la producción de la bilirrubina",
    "Aumento en la eliminación de amoníaco por los riñones",
    "Disminución en la producción de factores de la coagulación"
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 24,
    "question": "¿Cuál es una de las consecuencias fisiopatológicas involucradas en la insuficiencia hepatocítica?",
    "answer": ["Reducción en la capacidad de eliminación de toxinas"],
    "options": [
    "Reducción del tono GABA",
    "Aumento en la producción de bilis",
    "Aumento en la síntesis de glucógeno hepático",
    "Reducción en la capacidad de eliminación de toxinas"
    ],
    "discipline": "Fisiopato",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 25,
    "question": "¿Cuál de las siguientes opciones sobre la excreción de ceftriaxona es correcta?",
    "answer": ["Biliar próxima al 40%"],
    "options": [
    "Biliar próxima al 40%",
    "Secreción tubular en un 80%",
    "Pulmonar en un 50% y renal un 20%",
    "Hidrólisis por peptidasas plasmáticas"
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 26,
    "question": "¿Cuál de los siguientes antirretrovirales es un inhibidor de la transcriptasa inversa no nucleosídico?",
    "answer": ["Efavirenz"],
    "options": [
    "Efavirenz",
    "Darunavir",
    "Dolutegravir",
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 27,
    "question": "¿Cuál de las siguientes propiedades farmacocinéticas de fluconazol es correcta?",
    "answer": ["Alcanza niveles terapéuticos en líquido cefalorraquídeo."],
    "options": [
    "Presenta absorción oral cercana al 10%.",
    "Su eliminación es predominantemente hepática.",
    "Es inductor de diversas isoenzimas del citocromo P450.",
    "Alcanza niveles terapéuticos en líquido cefalorraquídeo."
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 28,
    "question": "¿Cuál de las siguientes vacunas disponible en el carné esquema de vacunación contiene bacterias vivas atenuadas?",
    "answer": ["BCG"],
    "options": [
    "BCG",
    "Pentavalente",
    "Triple bacteriana (DPT)",
    "Triple bacteriana acelular (dpaT)"
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 29,
    "question": "¿Cuál de los siguientes grupos farmacológicos pueden alterar la recirculación enterohepática de los estrógenos y disminuir su efecto anticonceptivo?",
    "answer": ["Antibióticos"],
    "options": [
    "Antiácidos",
    "Analgésicos",
    "Antibióticos",
    "Antiepilépticos"
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 30,
    "question": "¿Cuál de las siguientes opciones es una contraindicación de anticonceptivos orales combinados?",
    "answer": ["Migraña con aura"],
    "options": [
    "Dislipemia",
    "Hipotiroidismo",
    "Migraña con aura",
    "Tumores ováricos benignos"
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 31,
    "question": "¿Cuál de las siguientes opciones indica una conveniencia terapéutica de los anticonceptivos de progesterona inyectables?",
    "answer": ["Pueden ser usados durante la lactancia"],
    "options": [
    "Se administra a nivel subcutáneo",
    "Pueden ser usados durante la lactancia",
    "Es seguro en el sangrado uterino anormal",
    "Mayor adherencia por su aplicación mensual"
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 32,
    "question": "¿Cuál de los siguientes efectos adversos de los progestágenos puede explicarse por su efecto androgénico?",
    "answer": ["Aumento del acné facial"],
    "options": [
    "Descenso de peso",
    "Aumento del acné facial",
    "Irregularidad menstrual",
    "Insomnio de conciliación"
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 33,
    "question": "¿Cuál es una característica del mecanismo de acción genómico de los glucocorticoides?",
    "answer": ["Presenta similar afinidad por los receptores mineralocorticoideos"],
    "options": [
    "Aumenta la transcripción del gen de la COX-2",
    "Requiere administrar dosis altas para objetivar sus efectos",
    "Los receptores se encuentran ubicados en la membrana celular",
    "Presenta similar afinidad por los receptores mineralocorticoideos"
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 34,
    "question": "¿Cuál es el efecto adverso de los glucocorticoides de uso sistémico cuando se retiran de forma abrupta luego de un período de al menos 15 días de uso?",
    "answer": ["Insuficiencia suprarrenal aguda"],
    "options": [
    "Osteoporosis",
    "Hiperglucemia",
    "Insuficiencia suprarrenal aguda",
    "Disminución de crecimiento y desarrollo"
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 35,
    "question": "¿Cuál de los siguientes mecanismos podría explicar el efecto broncodilatador de las metilxantinas?",
    "answer": ["Inhibición de la fosfodiesterasa"],
    "options": [
    "Inhibición de la fosfodiesterasa",
    "Liberación de la interleucina-10",
    "Apoptosis de eosinófilos y neutrófilos",
    "Agonismo de receptores de adenosina"
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 37,
    "question": "¿Cuál de los siguientes constituye un efectos adversos de los antihistamínicos H1?",
    "answer": ["Clorfeniramina puede provocar ansiedad en pacientes pediátricos"],
    "options": [
    "Levocetirizina puede causar sedación",
    "Difenhidramina puede provocar bradicardia",
    "Clorfeniramina puede provocar ansiedad en pacientes pediátricos",
    "Loratadina puede provocar manifestaciones anticolinérgicas severas "],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 38,
    "question": "Con relación a las propiedades farmacocinéticas de los macrólidos. Marque la opción correcta.",
    "answer": ["Amplio volumen de distribución"],
    "options": [
    "Eliminación pulmonar",
    "Amplio volumen de distribución",
    "Baja unión a proteínas plasmáticas",
    "Metabolismo enzimático plasmático"
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 39,
    "question": "Respecto a los benzimidazoles, ¿cuál de las siguientes opciones sobre el mecanismo de acción de mebendazol es correcta?",
    "answer": ["Inhibición de la polimerización de microtúbulos al unirse a la tubulina β."],
    "options": [
    "Inmovilización de los organismos por polimerización de la tubulina α.",
    "Generación de radicales libres que dañan a los microtúbulos del verme.",
    "Inhibición de la polimerización de microtúbulos al unirse a la tubulina β.",
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 40,
    "question": "Indique cuál de los siguientes efectos adversos de los agonistas beta-2 adrenérgicos inhalatorios son de tipo A:",
    "answer": ["Taquicardia."],
    "options": [
    "Taquicardia.",
    "Hipertensión.",
    "Hiperpotasemia.",
    "Hipomagnesemia."
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 41,
    "question": "¿Cuál de los siguientes antiepilépticos produce como efecto adverso hiponatremia?",
    "answer": ["Carbamazepina."],
    "options": [
    "Fenitoína.",
    "Topiramato.",
    "Pregabalina.",
    "Carbamazepina."
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 42,
    "question": "Señale cuál de los siguientes antiepilépticos presenta un estrecho margen terapéutico:",
    "answer": ["Ácido valproico."],
    "options": [
    "Topiramato.",
    "Escitalopram.",
    "Levetiracetam.",
    "Ácido valproico."
    ],
    "discipline": "Farmaco",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 43,
    "question": "Al comienzo de los procesos de inflamación aguda, ¿cuál es la principal célula involucrada?",
    "answer": ["Neutrófilo"],
    "options": [
    "Linfocito",
    "Neutrófilo",
    "Macrófago",
    "Plasmocito"
    ],
    "discipline": "AnatoP",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 44,
    "question": "¿Cuál de los siguientes procesos de adaptación celular ocurre fisiológicamente en el epitelio de la glándula mamaria durante el embarazo?",
    "answer": ["Hiperplasia"],
    "options": [
    "Atrofia",
    "Hipertrofia",
    "Metaplasia",
    "Hiperplasia"
    ],
    "discipline": "AnatoP",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 45,
    "question": "¿Cuál de las siguientes opciones indica una característica de la necrosis caseosa?",
    "answer": ["Tiene aspecto blanquecino y friable y es característica de los granulomas tuberculoides."],
    "options": [
    "Tiene aspecto blanquecino y friable y es característica de los granulomas tuberculoides.",
    "Son áreas focales de destrucción de la grasa, con adipocitos necróticos que en su interior presentan depósitos de calcio basófilo.",
    "Tiene aspecto de masa viscosa con material necrótico que suele ser amarillento cremoso por la presencia de leucocitos muertos.",
    ],
    "discipline": "AnatoP",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 46,
    "question": "¿Cuál de las siguientes lesiones tisulares se caracteriza por presentar necrosis licuefactiva?",
    "answer": ["isquemia en el sistema nervioso central"],
    "options": [
    "tuberculosis pulmonar",
    "isquemia en el tejido cardíaco",
    "isquemia en el sistema nervioso central",
    "lesión tuberculosa en el sistema nervioso central"
    ],
    "discipline": "AnatoP",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 47,
    "question": "El granuloma de cuerpo extraño característicamente presenta:",
    "answer": ["Células gigantes multinucleadas que engloban el material extraño"],
    "options": [
    "Células gigantes multinucleadas que engloban el material extraño",
    "Células epitelioides con una corona linfocitaria rodeando el mterial extraño",
    "Células epitelioides que delimitan una zona de necrosis licuefactiva que contiene el cuerpo extraño",
    ],
    "discipline": "AnatoP",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 48,
    "question": "¿Cuál de los siguientes cambios en la morfología celular es característico del proceso de apoptosis?",
    "answer": ["El tamaño de la célula se reduce y el citoplasma es denso y eosinófilo"],
    "options": [
    "Ocurre un proceso de tumefacción celular",
    "El tamaño de la célula se reduce y el citoplasma es denso y eosinófilo",
    "El tamaño de la célula aumenta y se observa un núcleo con picnosis y ruptura de la membrana celular",
    "Se observa la formación de vacuolas citoplasmáticas y la liberación del contenido celular al espacio extracelular"
    ],
    "discipline": "AnatoP",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 49,
    "question": "El exudado es un líquido:",
    "answer": ["Con alto contenido en proteínas y presencia de células sanguíneas."],
    "options": [
    "Con apariencia clara y LDH bajo.",
    "Con apariencia clara y un pH> 7,2.",
    "Con bajo contenido en proteínas y pobre en células sanguíneas.",
    "Con alto contenido en proteínas y presencia de células sanguíneas."
    ],
    "discipline": "AnatoP",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 50,
    "question": "En la esteatosis ¿Qué sustancias se acumulan en el interior de las células parenquimatosas?",
    "answer": ["triglicéridos"],
    "options": [
    "proteínas",
    "glucógeno",
    "lipofuccina",
    "triglicéridos"
    ],
    "discipline": "AnatoP",
    "comment": "",
    },
    {
    "info_quest": "3er Parcial 2024",
    "numb": 51,
    "question": "En las primeras horas tras una injuria sobre un tejido, el tejido de granulación:",
    "answer": ["sufre una proliferación endotelial marcada"],
    "options": [
    "no sufre modificaciones",
    "sufre una proliferación endotelial marcada",
    "se compone principalmente de tejido fibroso y no muestra actividad vascular",
    ],
    "discipline": "AnatoP",
    "comment": "",
    },

];